spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:searcdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org.hibernate.SQL: INFO
---
external:
  kakao:
    api:
      uri: https://dapi.kakao.com/v2/local/search/keyword.json?
      key: e611ca2e6f7814e882c23dbc0b5491e7
  naver:
    api: https://openapi.naver.com/v1/search/local.json?
    client-id: nLVpM1bLgQDCkD7nNaUq
    client-secret: bIdM2DYoYX
---
token:
  secret-key: search
---